export default function ButtonPanel() {
  return (
    <div>
      <div>
        <button></button>
        <button></button>
        <button></button>
        <button></button>
      </div>
      <div>
        <button></button>
        <button></button>
        <button></button>
        <button></button>
      </div>
      <div>
        <button></button>
        <button></button>
        <button></button>
        <button></button>
      </div>
      <div>
        <button></button>
        <button></button>
        <button></button>
        <button></button>
      </div>
    </div>
  );
}